[tool.ruff]
line-length = 120


[tool.ruff.lint]
# E, F = Standard flake8 rules (syntax errors, undefined names)
# I    = Isort rules (this sorts your imports)
select = ["E", "F", "I"]

[tool.ruff.format]
quote-style = "double"

[project]
name = "gpt2-tinystories"
version = "0.1.0"
description = "GPT2 Trained on TinyStories Dataset"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "datasets>=4.4.1",
    "ipywidgets>=8.1.8",
    "matplotlib>=3.10.8",
    "numpy>=2.3.5",
    "python-dotenv>=1.2.1",
    "tiktoken>=0.12.0",
    "torch>=2.9.1",
    "wandb>=0.24.2",
]

[dependency-groups]
dev = [
    "ruff>=0.14.10",
]
